version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: dendes/e2-test
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
                  docker build .
#      - run:
#          name: Publish Docker Image to Docker Hub
#          command: |
#            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
#            echo 1
#            docker run -t ${IMAGE_NAME#*/} $IMAGE_NAME
#            echo 2
#            docker save ${IMAGE_NAME#*/} -o ${IMAGE_NAME#*/}.tar
#            echo 3
#            cat ${IMAGE_NAME#*/}.tar | docker load - ${IMAGE_NAME}:latest
#            docker push ${IMAGE_NAME}:latest
#  publish-latest:
#    executor: docker-publisher
#    steps:
#      - setup_remote_docker
#      - run:
#          name: Publish Docker Image to Docker Hub
#          command: |
#            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
#            IMAGE_TAG="0.0.${CIRCLE_BUILD_NUM}"
#            docker tag ${IMAGE_NAME#*/} $IMAGE_NAME:latest
#            docker push $IMAGE_NAME:latest
#            docker push $IMAGE_NAME:$IMAGE_TAG
#  publish-tag:
#    executor: docker-publisher
#    steps:
#      - setup_remote_docker
#      - run:
#          name: Publish Docker Image to Docker Hub
#          command: |
#            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
#            IMAGE_TAG=${CIRCLE_TAG/v/''}
#            docker tag ${IMAGE_NAME#*/} $IMAGE_NAME:latest
#            docker push $IMAGE_NAME:$IMAGE_TAG
workflows:
  version: 2
  build-python3:
    jobs:
      - build:
          filters:
            branches:
              only: python3
#      - publish-latest:
#          requires:
#            - build
#          filters:
#            branches:
#              only: python3
  build-tags:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
#      - publish-tag:
#          requires:
#            - build
#          filters:
#            tags:
#              only: /^v.*/
#            branches:
#              ignore: /.*/
