name: Enigma2 CI

on: [push, pull_request]

jobs:
  build:
    env:
      CC: "gcc-${{ matrix.gcc }}"
      CXX: "g++-${{ matrix.gcc }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        gcc: [8, 10]
        python: [2.7,3.8]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Builld it
      run: docker build --build-arg GCC=${{ matrix.gcc }} --build-arg PY=${{ matrix.python }} .
