name: Enigma2 CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        gcc: [8, 10]
        python: ["2.7","3.8"]
    steps:
    - uses: actions/checkout@v2
    - name: install gcc ${{ matrix.gcc }}
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get -q update
        sudo apt install g++-${{ matrix.gcc }}
    - name: install dev packages
      run: |
        sudo apt-get -q update
        sudo apt-get install \
        linux-libc-dev git build-essential libboost-python-dev libboost-system-dev \
        automake libtool zlib1g-dev gettext \
        swig libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
        libfreetype6-dev libsigc++-2.0-dev libxml2-dev libfribidi-dev \
        libssl-dev libavahi-client-dev libjpeg-turbo8-dev \
        libgif-dev
    - name: Installing Python 3.8
      if: ${{ matrix.python == "3.8" }}
      run: |
        sudo apt install python3.8-dev python3-pip
        sudo unlink /usr/bin/python
        sudo ln -s /usr/bin/python3.8 /usr/bin/python
        pip3 install --upgrade pip tox six
        python -V
    - name: Installing Python 2.7
      if: ${{ matrix.python == "2.7" }}
      run: |
        sudo apt install python2.7-dev python-pip
        pip install --upgrade pip tox six
        python -V
    - name: build enigma2 dependencies
      env: 
        CC: "gcc-${{ matrix.gcc }}"
        CXX: "g++-${{ matrix.gcc }}"
      run: |
        echo installing libdvbsi++
        pushd .
        cd /tmp
        git clone --depth 1 git://git.opendreambox.org/git/obi/libdvbsi++.git
        cd libdvbsi++
        autoreconf -i
        ./configure
        make
        sudo make install
        popd
        echo installing tuxbox
        pushd .
        cd /tmp
        git clone --depth 1 https://github.com/OpenPLi/tuxtxt.git
        cd tuxtxt/libtuxtxt
        autoreconf -i
        ./configure --with-boxtype=generic DVB_API_VERSION=5
        make
        sudo make install
        cd ../tuxtxt
        autoreconf -i
        ./configure --with-boxtype=generic DVB_API_VERSION=5
        make
        sudo make install
        popd
    - name: build enigma2
      env: 
        CC: "gcc-${{ matrix.gcc }}"
        CXX: "g++-${{ matrix.gcc }}"
      run: |
        echo compiling enigma2
        autoreconf -i
        ./configure --with-libsdl=no --with-boxtype=nobox --enable-dependency-tracking ac_cv_prog_c_openmp=-fopenmp --with-textlcd
        make
        python -m compileall .
        echo done!
