name: Enigma2 CI

on: [push, pull_request]

jobs:
  build:
    env:
      CC: "gcc-${{ matrix.gcc }}"
      CXX: "g++-${{ matrix.gcc }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        #gcc: [8, 10]
        gcc: [8]
        python: [2.7,3.8]
      fail-fast: false
    steps:
    - name: show env
      run: |
        env
        export
    - name: Set A
      run: |
        export A=foo
        export B=bar
        env | egrep "(A=|B=)"
        export | egrep "(A=|B=)"
    - name: show env again
      run: |
        env | egrep "(A=|B=)"
        export | egrep "(A=|B=)"
